name: flutter_advanced_button
description: An advanced button widget, that can be fully customized with size, text, color, radius of corners.
version: 1.0.1
author: Erfan Rahmati<erfanrht1384.com@gmail.com>
homepage: https://github.com/ErfanRht/flutter_advanced_button

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: